workflows: 

  sessionFlow: 

    states:

      ACTIVE:

        onTransitionEvent:
          - completePreviousEvent
          - createNewEvent
          - updateSessionTracking

        onEndSession:
          - completeSession

        onTimeout:
          - abortSession 